<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<form action="/album/add" method="post">
    <label for="titulo">Titulo</label>
    <input type="text" name="title" id="titulo">
    <label for="artista">Artista</label>
    <input type="text" name="artist" id="artista">
    <input type="submit" value="Crear Album">
</form>
</body>
</html>