<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form action="/album/edit/<?= $id ?>" method="post">
    <label for="">artista</label>
    <input type="text" name="artista">
    <label for="">titulo</label>
    <input type="text" name="titulo">
    <input type="submit">
</form>
</body>
</html>